# Generated by Django 3.2.6 on 2021-11-30 22:04

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalle de Pedidos',
                'db_table': 'pedidos_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad_resp', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Pedido',
                'verbose_name_plural': 'Detalle de Solicitudes de Pedidos',
                'db_table': 'pedidos_solicitud_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoSolicitudProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaOfertada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca Ofertada')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Pedido',
                'verbose_name_plural': 'Detalle de Solicitudes de Pedidos',
                'db_table': 'pedidos_solicitud_proveedor_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDetallePedidoSolicitud',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad_resp', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Detalle de Solicitud de Pedido',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPedidosSolicitud',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fechaLimite', models.DateTimeField(null=True, verbose_name='Fecha Límite')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(blank=True, default='', null=True)),
                ('analizado', models.BooleanField(blank=True, null=True)),
                ('resp_incompleta', models.BooleanField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Solicitud de Pedido',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PedidosSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fechaLimite', models.DateTimeField(null=True, verbose_name='Fecha Límite')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(blank=True, default='', null=True)),
                ('analizado', models.BooleanField(blank=True, null=True)),
                ('resp_incompleta', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Pedido',
                'verbose_name_plural': 'Solicitudes de Pedidos',
                'db_table': 'pedidos_solicitud',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoSolicitudProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('enviado', models.DateTimeField(verbose_name='Fecha y Hora de envío correo electrónico')),
                ('visto', models.DateTimeField(null=True, verbose_name='Fecha y Hora de visto el formulario')),
                ('respuesta', models.DateTimeField(null=True, verbose_name='Fecha y Hora de respuesta del formulario')),
                ('hash', models.CharField(max_length=66, null=True, verbose_name='Hash de solicitud')),
                ('pedidoSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidossolicitud', verbose_name='Pedido de Solicitud')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Solicitud de Pedido Proveedor',
                'verbose_name_plural': 'Solicitudes de Pedidos Proveedor',
                'db_table': 'pedidos_solicitud_proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(blank=True, default='', null=True)),
                ('pedidoSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidossolicitud', verbose_name='Pedido de Solicitud')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['id'],
            },
        ),
    ]
