# Generated by Django 3.2.6 on 2021-12-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_initial'),
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.proveedores', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
