# Generated by Django 3.2.6 on 2021-12-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20211202_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='marcaOfertada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca Ofertada'),
        ),
    ]
