# Generated by Django 3.2.6 on 2021-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedidos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedidossolicitud',
            name='realizado',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='pedidossolicitud',
            name='realizado',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
