# Generated by Django 3.2.6 on 2021-10-08 18:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registroNoExitosoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSuceso', models.DateTimeField(default=datetime.datetime(2021, 10, 8, 15, 9, 12, 492392))),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='notificacionUsuarios_Tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot_telegram.registronoexitosocliente', verbose_name='registro log asociado')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario notificado')),
            ],
        ),
    ]
