# Generated by Django 3.2.6 on 2021-11-11 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0077_auto_20211110_1842'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajos', '0012_historicaldetalleplanificacionessemanales_historicalplanificacionessemanales'),
    ]

    operations = [
        migrations.CreateModel(
            name='seguimientoTrabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantVecesNotif_dia', models.IntegerField(default=0, verbose_name='Cantidad de veces notificadas en el día')),
                ('cantVecesNotif_total', models.IntegerField(default=0, verbose_name='Cantidad de veces TOTALES notificadas (1 por día)')),
                ('respuestaUser', models.CharField(blank=True, max_length=40, null=True, verbose_name='Respuesta')),
                ('fechaEnvio', models.DateTimeField(blank=True, null=True)),
                ('fechaRespuesta', models.DateTimeField(blank=True, null=True)),
                ('notif_por_sist', models.IntegerField(default=0, verbose_name='Cantidad de veces notificadas por Sistema.')),
                ('inicialUserAsig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario_inicial', to=settings.AUTH_USER_MODEL, verbose_name='Inicial. Usuario asociado')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos', verbose_name='Trabajo asociado')),
                ('ultUserAsig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario_final', to=settings.AUTH_USER_MODEL, verbose_name='Ult. Usuario asociado')),
            ],
            options={
                'verbose_name': 'Seguimiento de estado de trabajo',
                'verbose_name_plural': 'Seguimiento de estado de trabajos',
                'db_table': 'bot_seguimientoTrabajos',
                'ordering': ['trabajo'],
            },
        ),
        migrations.CreateModel(
            name='respuestaTrabajoFinalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRespuesta', models.DateTimeField(blank=True, null=True)),
                ('respuesta_puntual', models.DateField(blank=True, null=True)),
                ('respuesta_generica', models.CharField(blank=True, max_length=20, null=True, verbose_name='Respuesta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.clientes', verbose_name='Cliente que respondió')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos', verbose_name='Trabajo asociado')),
            ],
            options={
                'verbose_name': 'Respuesta de trabajo finalizado',
                'verbose_name_plural': 'Respuestas de trabajo finalizado',
                'db_table': 'bot_respuestaTrabajoFinalziado',
                'ordering': ['fechaRespuesta'],
            },
        ),
        migrations.CreateModel(
            name='notifUsuariosBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a notificar')),
            ],
            options={
                'verbose_name': 'Notificacion de incidencia',
                'verbose_name_plural': 'Notificaciones de incidencia',
                'db_table': 'bot_usuarios_a_notificar',
                'ordering': ['usuario_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalseguimientoTrabajos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantVecesNotif_dia', models.IntegerField(default=0, verbose_name='Cantidad de veces notificadas en el día')),
                ('cantVecesNotif_total', models.IntegerField(default=0, verbose_name='Cantidad de veces TOTALES notificadas (1 por día)')),
                ('respuestaUser', models.CharField(blank=True, max_length=40, null=True, verbose_name='Respuesta')),
                ('fechaEnvio', models.DateTimeField(blank=True, null=True)),
                ('fechaRespuesta', models.DateTimeField(blank=True, null=True)),
                ('notif_por_sist', models.IntegerField(default=0, verbose_name='Cantidad de veces notificadas por Sistema.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inicialUserAsig', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Inicial. Usuario asociado')),
                ('trabajo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trabajos.trabajos', verbose_name='Trabajo asociado')),
                ('ultUserAsig', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ult. Usuario asociado')),
            ],
            options={
                'verbose_name': 'historical Seguimiento de estado de trabajo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalrespuestaTrabajoFinalizado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fechaRespuesta', models.DateTimeField(blank=True, null=True)),
                ('respuesta_puntual', models.DateField(blank=True, null=True)),
                ('respuesta_generica', models.CharField(blank=True, max_length=20, null=True, verbose_name='Respuesta')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.clientes', verbose_name='Cliente que respondió')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trabajos.trabajos', verbose_name='Trabajo asociado')),
            ],
            options={
                'verbose_name': 'historical Respuesta de trabajo finalizado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalnotifUsuariosBot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario a notificar')),
            ],
            options={
                'verbose_name': 'historical Notificacion de incidencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
