# Generated by Django 3.2.6 on 2021-11-29 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp', '0002_initial'),
        ('bot_telegram', '0001_initial'),
        ('trabajos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='inicialUserAsig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario_inicial', to=settings.AUTH_USER_MODEL, verbose_name='Inicial. Usuario asociado'),
        ),
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos', verbose_name='Trabajo asociado'),
        ),
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='ultUserAsig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario_final', to=settings.AUTH_USER_MODEL, verbose_name='Ult. Usuario asociado'),
        ),
        migrations.AddField(
            model_name='respuestatrabajofinalizado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.clientes', verbose_name='Cliente que respondió'),
        ),
        migrations.AddField(
            model_name='respuestatrabajofinalizado',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos', verbose_name='Trabajo asociado'),
        ),
        migrations.AddField(
            model_name='notifusuariosbot',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a notificar'),
        ),
        migrations.AddField(
            model_name='historicalseguimientotrabajos',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalseguimientotrabajos',
            name='inicialUserAsig',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Inicial. Usuario asociado'),
        ),
        migrations.AddField(
            model_name='historicalseguimientotrabajos',
            name='trabajo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trabajos.trabajos', verbose_name='Trabajo asociado'),
        ),
        migrations.AddField(
            model_name='historicalseguimientotrabajos',
            name='ultUserAsig',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ult. Usuario asociado'),
        ),
        migrations.AddField(
            model_name='historicalrespuestatrabajofinalizado',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.clientes', verbose_name='Cliente que respondió'),
        ),
        migrations.AddField(
            model_name='historicalrespuestatrabajofinalizado',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrespuestatrabajofinalizado',
            name='trabajo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trabajos.trabajos', verbose_name='Trabajo asociado'),
        ),
        migrations.AddField(
            model_name='historicalnotifusuariosbot',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnotifusuariosbot',
            name='usuario_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario a notificar'),
        ),
    ]
