# Generated by Django 3.2.6 on 2021-10-08 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0003_auto_20211008_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 16, 47, 13, 525674), null=True),
        ),
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 16, 47, 13, 525285)),
        ),
    ]
