# Generated by Django 3.2.6 on 2021-10-08 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0004_auto_20211008_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 17, 5, 37, 448151), null=True),
        ),
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 17, 5, 37, 447827)),
        ),
    ]
