# Generated by Django 3.2.6 on 2021-10-09 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0006_auto_20211009_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 14, 41, 30, 476503), null=True),
        ),
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 14, 41, 30, 476182)),
        ),
    ]
