# Generated by Django 3.2.6 on 2021-10-09 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0007_auto_20211009_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 14, 57, 18, 946469), null=True),
        ),
        migrations.AlterField(
            model_name='registronoexitosocliente',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 14, 57, 18, 946141)),
        ),
    ]
