# Generated by Django 3.2.6 on 2021-10-12 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0010_remove_detalleplanificacionessemanales_dia'),
        ('erp', '0048_merge_20211009_1441'),
        ('bot_telegram', '0009_auto_20211010_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 12, 15, 17, 14, 889376), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 15, 17, 14, 888998)),
        ),
        migrations.CreateModel(
            name='respuestaTrabajoFinalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRespuesta', models.DateTimeField(default=datetime.datetime(2021, 10, 12, 15, 17, 14, 895540))),
                ('respuesta', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.clientes', verbose_name='Cliente que respondió')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos', verbose_name='Trabajo asociado')),
            ],
            options={
                'verbose_name': 'Respuesta de trabajo finalizado',
                'verbose_name_plural': 'Respuestas de trabajo finalizado',
                'db_table': 'bot_respuestaTrabajoFinalziado',
                'ordering': ['fechaRespuesta'],
            },
        ),
    ]
