# Generated by Django 3.2.6 on 2021-10-12 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0010_auto_20211012_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 12, 15, 25, 6, 288069), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 15, 25, 6, 287747)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 15, 25, 6, 293957)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='respuesta',
            field=models.CharField(max_length=20, null=True, verbose_name='Respuesta'),
        ),
    ]
