# Generated by Django 3.2.6 on 2021-10-12 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0011_auto_20211012_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestatrabajofinalizado',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='respuestatrabajofinalizado',
            name='respuesta_generica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Respuesta'),
        ),
        migrations.AddField(
            model_name='respuestatrabajofinalizado',
            name='respuesta_puntual',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 12), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 12, 16, 24, 54, 188072), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 16, 24, 54, 187751)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 12, 16, 24, 54, 193956), null=True),
        ),
    ]
