# Generated by Django 3.2.6 on 2021-10-12 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0012_auto_20211012_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 12, 16, 26, 42, 821515), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 16, 26, 42, 821174)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 12, 16, 26, 42, 828154), null=True),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='respuesta_puntual',
            field=models.DateField(blank=True, null=True),
        ),
    ]
