# Generated by Django 3.2.6 on 2021-10-28 13:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0010_remove_detalleplanificacionessemanales_dia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_telegram', '0023_auto_20211028_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 10, 59, 21, 181252), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 10, 59, 21, 180886)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 28, 10, 59, 21, 187341), null=True),
        ),
        migrations.CreateModel(
            name='seguimientoTrabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultPorcentajeAvance', models.IntegerField(default=0)),
                ('cantVecesNotif', models.IntegerField(default=0)),
                ('inicialUserAsig', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario_inicial', to=settings.AUTH_USER_MODEL, verbose_name='Inicial. Usuario asociado')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos', verbose_name='Trabajo asociado')),
                ('ultUserAsig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario_final', to=settings.AUTH_USER_MODEL, verbose_name='Ult. Usuario asociado')),
            ],
            options={
                'verbose_name': 'Seguimiento de estado de trabajo',
                'verbose_name_plural': 'Seguimiento de estado de trabajos',
                'db_table': 'bot_seguimientoTrabajos',
                'ordering': ['trabajo'],
            },
        ),
    ]
