# Generated by Django 3.2.6 on 2021-10-30 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0026_auto_20211030_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='respuestaUser',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 30, 19, 59, 49, 559919), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 19, 59, 49, 559555)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 30, 19, 59, 49, 567164), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='ultPorcentajeAvance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
