# Generated by Django 3.2.6 on 2021-10-31 00:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_telegram', '0027_auto_20211030_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 30, 21, 18, 22, 716678), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 21, 18, 22, 716300)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 30, 21, 18, 22, 723380), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='inicialUserAsig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario_inicial', to=settings.AUTH_USER_MODEL, verbose_name='Inicial. Usuario asociado'),
        ),
    ]
