# Generated by Django 3.2.6 on 2021-10-31 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0028_auto_20211030_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='fechaEnvio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 0, 40, 36, 763027)),
        ),
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 31, 0, 40, 36, 753146), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 0, 40, 36, 752793)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 31, 0, 40, 36, 759911), null=True),
        ),
    ]
