# Generated by Django 3.2.6 on 2021-10-31 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0029_auto_20211031_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 31, 1, 14, 54, 977356), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 1, 14, 54, 977004)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 31, 1, 14, 54, 984064), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='fechaEnvio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 1, 14, 54, 987164)),
        ),
    ]
