# Generated by Django 3.2.6 on 2021-10-31 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0031_auto_20211031_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientotrabajos',
            name='ultPorcentajeAvance',
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 31, 1, 45, 7, 5368), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 1, 45, 7, 5036)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 31, 1, 45, 7, 11536), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='fechaEnvio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 1, 45, 7, 14323)),
        ),
    ]
