# Generated by Django 3.2.6 on 2021-10-31 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0032_auto_20211031_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientotrabajos',
            name='cantVecesNotif',
        ),
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='cantVecesNotif_dia',
            field=models.IntegerField(default=0, verbose_name='Cantidad de veces notificadas en el día'),
        ),
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='cantVecesNotif_total',
            field=models.IntegerField(default=0, verbose_name='Cantidad de veces TOTALES notificadas (1 por día)'),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 31, 13, 42, 56, 226449), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 13, 42, 56, 226115)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 31, 13, 42, 56, 232347), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='fechaEnvio',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 13, 42, 56, 235090)),
        ),
    ]
