# Generated by Django 3.2.6 on 2021-11-02 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0033_auto_20211031_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientotrabajos',
            name='notif_por_sist',
            field=models.IntegerField(default=0, verbose_name='Cantidad de veces notificadas por Sistema.'),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 2, 15, 34, 20, 616604), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 15, 34, 20, 616255)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 2, 15, 34, 20, 623351), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='fechaEnvio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 2, 15, 34, 20, 626407), null=True),
        ),
    ]
