# Generated by Django 3.2.6 on 2021-11-06 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0034_auto_20211102_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 5, 21, 39, 25, 203458), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 21, 39, 25, 203088)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 5, 21, 39, 25, 210168), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='fechaEnvio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 5, 21, 39, 25, 213171), null=True),
        ),
    ]
