# Generated by Django 3.2.6 on 2021-11-06 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0035_auto_20211105_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 5, 21, 44, 10, 419209), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 21, 44, 10, 418890)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 5, 21, 44, 10, 425142), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='fechaEnvio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 5, 21, 44, 10, 427930), null=True),
        ),
    ]
