# Generated by Django 3.2.6 on 2021-11-07 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_telegram', '0036_auto_20211105_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaRevision',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 6, 22, 16, 16, 325113), null=True),
        ),
        migrations.AlterField(
            model_name='registrobotincidencias',
            name='fechaSuceso',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 22, 16, 16, 324792)),
        ),
        migrations.AlterField(
            model_name='respuestatrabajofinalizado',
            name='fechaRespuesta',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 6, 22, 16, 16, 331181), null=True),
        ),
        migrations.AlterField(
            model_name='seguimientotrabajos',
            name='fechaEnvio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
