# Generated by Django 3.2.6 on 2021-09-27 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0023_alter_empresa_passwordemail'),
        ('erp', '0044_alter_detalleserviciosventa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrada', models.DateField(verbose_name='Fecha de Entrada')),
                ('fechaSalida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('percepcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fichaTrabajo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ficha de Trabajo Asociada')),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.clientes', verbose_name='Cliente')),
                ('estadoTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.estados', verbose_name='Estado de Trabajo')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.modelos', verbose_name='Modelo')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.prioridades', verbose_name='Prioridad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuarioAsignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuarioAsignado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'db_table': 'trabajos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServiciosTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('estado', models.BooleanField(default=False)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.servicios')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos')),
            ],
            options={
                'verbose_name': 'Detalle de Servicios - Trabajo',
                'verbose_name_plural': 'Detalle de Servicios - Trabajos',
                'db_table': 'trabajos_detalle_servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProductosTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('estado', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos')),
            ],
            options={
                'verbose_name': 'Detalle de Productos - Trabajo',
                'verbose_name_plural': 'Detalle de Productos - Trabajos',
                'db_table': 'trabajos_detalle_productos',
                'ordering': ['id'],
            },
        ),
    ]
