# Generated by Django 3.2.6 on 2021-09-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0023_alter_empresa_passwordemail'),
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='estado',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='estadoTrabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.estados', verbose_name='Estado de Trabajo'),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.prioridades', verbose_name='Prioridad'),
        ),
    ]
