# Generated by Django 3.2.6 on 2021-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20210928_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='estadoTrabajo',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PLANIFICADO', 'PLANIFICADO'), ('PROCESO', 'EN PROCESO'), ('FINALIZADO', 'FINALIZADO'), ('ENTREGADO', 'ENTREGADO')], default='PENDIENTE', max_length=11),
        ),
    ]
