# Generated by Django 3.2.6 on 2021-09-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_alter_trabajos_estadotrabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajos',
            name='estado',
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='estadoTrabajo',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PLANIFICADO', 'PLANIFICADO'), ('PROCESO', 'EN PROCESO'), ('FINALIZADO', 'FINALIZADO'), ('ENTREGADO', 'ENTREGADO'), ('CANCELADO', 'CANCELADO')], default='PENDIENTE', max_length=11),
        ),
    ]
