# Generated by Django 3.2.6 on 2021-09-29 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajos', '0004_auto_20210928_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproductostrabajo',
            name='fechaDetalle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleproductostrabajo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='detalleserviciostrabajo',
            name='fechaDetalle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleserviciostrabajo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
