# Generated by Django 3.2.6 on 2021-09-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0025_auto_20210930_1609'),
        ('trabajos', '0005_auto_20210929_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='estadoTrabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.estados', verbose_name='Estado Trabajo'),
        ),
    ]
