# Generated by Django 3.2.6 on 2021-10-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0006_alter_trabajos_estadotrabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionTrabajosSemanales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'Planificación Semanal de Trabajos',
                'verbose_name_plural': 'Planificaciones Semanales de Trabajos',
                'db_table': 'trabajos_planificaciones_semanales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePlanificacionTrabajosSemanales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('dia', models.PositiveIntegerField(default=1)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.planificaciontrabajossemanales')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trabajos.trabajos')),
            ],
            options={
                'verbose_name': 'Detalle Planificación Semanal de Trabajos',
                'verbose_name_plural': 'Detalles de Planificaciones Semanales de Trabajos',
                'db_table': 'trabajos_detalle_planificaciones_semanales',
                'ordering': ['id'],
            },
        ),
    ]
