# Generated by Django 3.2.6 on 2021-10-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0007_detalleplanificaciontrabajossemanales_planificaciontrabajossemanales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePlanificacionTrabajosSemanales',
            new_name='DetallePlanificacionesSemanales',
        ),
        migrations.RenameModel(
            old_name='PlanificacionTrabajosSemanales',
            new_name='PlanificacionesSemanales',
        ),
    ]
