# Generated by Django 3.2.6 on 2021-10-08 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajos', '0008_auto_20211006_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacionessemanales',
            name='nombre',
        ),
        migrations.AddField(
            model_name='planificacionessemanales',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios', verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
