# Generated by Django 3.2.6 on 2021-09-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de IVA')),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name': 'Tipo de IVA',
                'verbose_name_plural': 'Tipos de IVA',
                'db_table': 'parametros_iva',
                'ordering': ['nombre'],
            },
        ),
    ]
