# Generated by Django 3.2.6 on 2021-09-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposiva',
            name='iva',
            field=models.DecimalField(decimal_places=3, default=0.21, max_digits=9, verbose_name='Porcentaje'),
        ),
    ]
