# Generated by Django 3.2.6 on 2021-12-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioridades',
            options={'ordering': ['plazoPrioridad'], 'verbose_name': 'Prioridad de Trabajo', 'verbose_name_plural': 'Prioridades de Trabajos'},
        ),
    ]
