# Generated by Django 3.2.6 on 2021-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_prioridades_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionespago',
            name='pagoDiferido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcondicionespago',
            name='pagoDiferido',
            field=models.BooleanField(default=False),
        ),
    ]
