# Generated by Django 3.2.6 on 2021-09-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_tiposiva_iva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposiva',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de IVA', 'verbose_name_plural': 'Tipos de IVA'},
        ),
    ]
