# Generated by Django 3.2.6 on 2021-09-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_alter_tiposiva_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Condición frente al IVA')),
            ],
            options={
                'verbose_name': 'Condición frente al IVA',
                'verbose_name_plural': 'Condiciones frente al IVA',
                'db_table': 'parametros_condicion_iva',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelTable(
            name='tiposiva',
            table='parametros_tipos_iva',
        ),
    ]
