# Generated by Django 3.2.6 on 2021-09-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_auto_20210907_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CondicionIVA',
            new_name='CondicionesIVA',
        ),
    ]
