# Generated by Django 3.2.6 on 2021-09-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0006_rename_condicioniva_condicionesiva'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='condicionesiva',
            table='parametros_condiciones_iva',
        ),
    ]
