# Generated by Django 3.2.6 on 2021-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_alter_condicionesiva_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Condición de Pago')),
            ],
            options={
                'verbose_name': 'Condición de Pago',
                'verbose_name_plural': 'Condiciones de Pagos',
                'db_table': 'parametros_condiciones_pagos',
                'ordering': ['id'],
            },
        ),
    ]
