# Generated by Django 3.2.6 on 2021-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_condicionespago'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposComprobantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Comprobante')),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de Comprobantes',
                'db_table': 'parametros_tipos_comprobantes',
                'ordering': ['nombre'],
            },
        ),
    ]
