# Generated by Django 3.2.6 on 2021-09-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0011_auto_20210912_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estado Trabajo',
                'verbose_name_plural': 'Estados Trabajos',
                'db_table': 'parametros_estados_trabajos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Prioridad de Trabajo',
                'verbose_name_plural': 'Prioridades de Trabajos',
                'db_table': 'parametros_prioridades_trabajos',
                'ordering': ['nombre'],
            },
        ),
    ]
