# Generated by Django 3.2.6 on 2021-09-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0012_estados_prioridad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prioridad',
            new_name='Prioridades',
        ),
    ]
