# Generated by Django 3.2.6 on 2021-09-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0013_rename_prioridad_prioridades'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioridades',
            name='plazoPrioridad',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de PLazo'),
        ),
    ]
