# Generated by Django 3.2.6 on 2021-09-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0014_prioridades_plazoprioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposPercepciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('percepcion', models.DecimalField(decimal_places=2, default=21, max_digits=9, verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name': 'Tipo de Percepción',
                'verbose_name_plural': 'Tipos de Percepciones',
                'db_table': 'parametros_tipos_percepciones',
                'ordering': ['id'],
            },
        ),
    ]
