# Generated by Django 3.2.6 on 2021-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0015_tipospercepciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipospercepciones',
            name='percepcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Porcentaje'),
        ),
    ]
