# Generated by Django 3.2.6 on 2021-09-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0016_alter_tipospercepciones_percepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pagos',
                'db_table': 'parametros_medios_pagos',
                'ordering': ['id'],
            },
        ),
    ]
