# Generated by Django 3.2.6 on 2021-09-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0018_auto_20210917_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposiva',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=9, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='tipospercepciones',
            name='percepcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Porcentaje'),
        ),
    ]
