# Generated by Django 3.2.6 on 2021-09-17 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografico', '0004_auto_20210904_1549'),
        ('parametros', '0019_auto_20210917_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('cuit', models.CharField(max_length=11, unique=True, verbose_name='Cuit')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Dirección de correo electrónico')),
                ('passwordEmail', models.CharField(max_length=128)),
                ('botTelegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bot Telegram')),
                ('tokenTelegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token Telegram')),
                ('facebook', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Cuenta de Facebook')),
                ('instagram', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Cuenta de Instagram')),
                ('paginaWeb', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Dirección de Página Web')),
                ('cbu', models.CharField(blank=True, max_length=22, null=True, verbose_name='Clave CBU/CVU')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias')),
                ('nroCuenta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Cuenta')),
                ('condicionIVA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionesiva', verbose_name='Condición frente al IVA')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Datos Empresa',
                'db_table': 'parametros_empresa',
            },
        ),
    ]
