# Generated by Django 3.2.6 on 2021-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0021_auto_20210917_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(max_length=13, unique=True, verbose_name='Cuit'),
        ),
    ]
