# Generated by Django 3.2.6 on 2021-09-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0022_alter_empresa_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='passwordEmail',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
