# Generated by Django 3.2.6 on 2021-09-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0023_alter_empresa_passwordemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='estados',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
