# Generated by Django 3.2.6 on 2021-09-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0024_estados_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estados',
            options={'ordering': ['orden'], 'verbose_name': 'Estado Trabajo', 'verbose_name_plural': 'Estados Trabajos'},
        ),
        migrations.CreateModel(
            name='EstadoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.estados', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Estado Trabajo Especial',
                'verbose_name_plural': 'Estado Trabajo Especial',
                'db_table': 'parametros_estado_trabajo_especial',
            },
        ),
    ]
