# Generated by Django 3.2.6 on 2021-09-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0026_auto_20210930_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoparametros',
            name='estadoEspecial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoEspecial', to='parametros.estados', verbose_name='Trabajo Especial'),
        ),
        migrations.AlterField(
            model_name='estadoparametros',
            name='estadoInicial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoInicial', to='parametros.estados', verbose_name='Trabajo Normal'),
        ),
    ]
