# Generated by Django 3.2.6 on 2021-09-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0027_auto_20210930_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoparametros',
            name='estadoCancelado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoCancelado', to='parametros.estados', verbose_name='Trabajo Cancelado'),
            preserve_default=False,
        ),
    ]
