# Generated by Django 3.2.6 on 2021-09-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0028_estadoparametros_estadocancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoparametros',
            name='estadoCancelado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoCancelado', to='parametros.estados', verbose_name='Trabajo Cancelado'),
        ),
        migrations.AlterField(
            model_name='estadoparametros',
            name='estadoEspecial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoEspecial', to='parametros.estados', verbose_name='Trabajo Especial'),
        ),
        migrations.AlterField(
            model_name='estadoparametros',
            name='estadoInicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoInicial', to='parametros.estados', verbose_name='Trabajo Normal'),
        ),
    ]
