# Generated by Django 3.2.6 on 2021-09-30 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0029_auto_20210930_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoparametros',
            name='estadoFinalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoFinalizado', to='parametros.estados', verbose_name='Trabajo Especial'),
        ),
    ]
