# Generated by Django 3.2.6 on 2021-09-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0030_estadoparametros_estadofinalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoparametros',
            options={},
        ),
        migrations.AlterModelTable(
            name='estadoparametros',
            table=None,
        ),
    ]
