# Generated by Django 3.2.6 on 2021-09-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0031_auto_20210930_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoparametros',
            options={'verbose_name': 'Estado de Trabajo Parámetros', 'verbose_name_plural': 'Estado de Trabajos Parámetros'},
        ),
        migrations.AlterModelTable(
            name='estadoparametros',
            table='parametros_estado_trabajo_parametros',
        ),
    ]
