# Generated by Django 3.2.6 on 2021-10-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0033_auto_20210930_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoparametros',
            name='estadoEntregado',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoEntregado', to='parametros.estados', verbose_name='Trabajo Entregado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadoparametros',
            name='estadoFinalizado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoFinalizado', to='parametros.estados', verbose_name='Trabajo Finalizado'),
        ),
    ]
