# Generated by Django 3.2.6 on 2021-10-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0034_auto_20211002_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoparametros',
            name='estadoPlanificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadoPlanificado', to='parametros.estados', verbose_name='Trabajo Planificado'),
            preserve_default=False,
        ),
    ]
