# Generated by Django 3.2.6 on 2021-12-01 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geografico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprovincias',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprovincias',
            name='pais',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geografico.paises', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='historicalpaises',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocalidades',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocalidades',
            name='pais',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geografico.paises', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='historicallocalidades',
            name='provincia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geografico.provincias', verbose_name='Provincia'),
        ),
        migrations.AlterUniqueTogether(
            name='provincias',
            unique_together={('pais', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='localidades',
            unique_together={('pais', 'provincia', 'nombre')},
        ),
    ]
