# Generated by Django 3.2.6 on 2021-08-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geografico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidades',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='provincias',
            name='estado',
        ),
    ]
