# Generated by Django 3.2.6 on 2021-08-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geografico', '0002_auto_20210818_1300'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='localidades',
            table='geografico_localidades',
        ),
        migrations.AlterModelTable(
            name='paises',
            table='geografico_paises',
        ),
        migrations.AlterModelTable(
            name='provincias',
            table='geografico_provincias',
        ),
    ]
