# Generated by Django 3.2.6 on 2021-09-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0023_alter_empresa_passwordemail'),
        ('erp', '0044_alter_detalleserviciosventa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestosBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.modelos', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Presupuesto Base',
                'verbose_name_plural': 'Presupuestos Base',
                'db_table': 'presupuesto_base',
                'ordering': ['id'],
                'unique_together': {('modelo', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='DetalleServiciosPresupuestoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('presupuestoBase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='presupuestos.presupuestosbase')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.servicios')),
            ],
            options={
                'verbose_name': 'Detalle de Servicios - Presupuesto Base',
                'verbose_name_plural': 'Detalle de Servicios - Presupuestos Base',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProductosPresupuestoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('presupuestoBase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='presupuestos.presupuestosbase')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Productos - Presupuesto Base',
                'verbose_name_plural': 'Detalle de Productos - Presupuestos Base',
                'ordering': ['id'],
            },
        ),
    ]
