# Generated by Django 3.2.6 on 2021-09-22 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_alter_detalleserviciosventa_options'),
        ('parametros', '0023_alter_empresa_passwordemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleproductospresupuestobase',
            table='presupuestos_base_detalle_productos',
        ),
        migrations.AlterModelTable(
            name='detalleserviciospresupuestobase',
            table='presupuestos_base_detalle_servicios',
        ),
        migrations.AlterModelTable(
            name='presupuestosbase',
            table='presupuestos_base',
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('validez', models.PositiveIntegerField(default=0, verbose_name='Validez del Presupuesto')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('percepcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=False)),
                ('observaciones', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.clientes', verbose_name='Cliente')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.modelos', verbose_name='Modelo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuestos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServiciosPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='presupuestos.presupuestos')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.servicios')),
            ],
            options={
                'verbose_name': 'Detalle de Servicios - Presupuesto',
                'verbose_name_plural': 'Detalle de Servicios - Presupuestos',
                'db_table': 'presupuestos_detalle_servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProductosPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='presupuestos.presupuestos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Productos - Presupuesto',
                'verbose_name_plural': 'Detalle de Productos - Presupuestos',
                'db_table': 'presupuestos_detalle_productos',
                'ordering': ['id'],
            },
        ),
    ]
