# Generated by Django 3.2.6 on 2021-11-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presupuestos', '0001_initial'),
        ('parametros', '0002_initial'),
        ('erp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='plantillapresupuestos',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.modelos', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='historicalpresupuestos',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.clientes', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalpresupuestos',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpresupuestos',
            name='modelo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.modelos', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='historicalpresupuestos',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalplantillapresupuestos',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalplantillapresupuestos',
            name='modelo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.modelos', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciospresupuesto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciospresupuesto',
            name='presupuesto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='presupuestos.presupuestos'),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciospresupuesto',
            name='servicio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.servicios'),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciosplantillapresupuesto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciosplantillapresupuesto',
            name='presupuestoPlantilla',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='presupuestos.plantillapresupuestos'),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciosplantillapresupuesto',
            name='servicio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.servicios'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductospresupuesto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductospresupuesto',
            name='presupuesto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='presupuestos.presupuestos'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductospresupuesto',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.productos'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductosplantillapresupuesto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductosplantillapresupuesto',
            name='presupuestoPlantilla',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='presupuestos.plantillapresupuestos'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductosplantillapresupuesto',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.productos'),
        ),
        migrations.AddField(
            model_name='detalleserviciospresupuesto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='presupuestos.presupuestos'),
        ),
        migrations.AddField(
            model_name='detalleserviciospresupuesto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.servicios'),
        ),
        migrations.AddField(
            model_name='detalleserviciosplantillapresupuesto',
            name='presupuestoPlantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='presupuestos.plantillapresupuestos'),
        ),
        migrations.AddField(
            model_name='detalleserviciosplantillapresupuesto',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.servicios'),
        ),
        migrations.AddField(
            model_name='detalleproductospresupuesto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='presupuestos.presupuestos'),
        ),
        migrations.AddField(
            model_name='detalleproductospresupuesto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos'),
        ),
        migrations.AddField(
            model_name='detalleproductosplantillapresupuesto',
            name='presupuestoPlantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='presupuestos.plantillapresupuestos'),
        ),
        migrations.AddField(
            model_name='detalleproductosplantillapresupuesto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillapresupuestos',
            unique_together={('modelo', 'descripcion')},
        ),
    ]
