# Generated by Django 3.2.6 on 2021-09-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_auto_20210922_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproductospresupuestobase',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detalleproductospresupuestobase',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='detalleserviciospresupuestobase',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detalleserviciospresupuestobase',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='presupuestosbase',
            name='total',
        ),
    ]
