# Generated by Django 3.2.6 on 2021-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_auto_20210923_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='validez',
            field=models.PositiveIntegerField(default=1, verbose_name='Validez del Presupuesto'),
        ),
    ]
