# Generated by Django 3.2.6 on 2021-09-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0023_alter_empresa_passwordemail'),
        ('erp', '0044_alter_detalleserviciosventa_options'),
        ('presupuestos', '0005_alter_presupuestos_observaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetalleServiciosPresupuestoBase',
            new_name='DetalleProductosPlantillaPresupuesto',
        ),
        migrations.RenameModel(
            old_name='DetalleProductosPresupuestoBase',
            new_name='DetalleServiciosPlantillaPresupuesto',
        ),
        migrations.RenameModel(
            old_name='PresupuestosBase',
            new_name='PlantillaPresupuestos',
        ),
        migrations.AlterModelOptions(
            name='detalleproductosplantillapresupuesto',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Productos - Plantilla Presupuesto', 'verbose_name_plural': 'Detalle de Productos - Plantilla de Presupuesto'},
        ),
        migrations.AlterModelOptions(
            name='detalleserviciosplantillapresupuesto',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Servicios - Plantilla Presupuesto', 'verbose_name_plural': 'Detalle de Servicios - Plantilla Presupuesto'},
        ),
        migrations.RenameField(
            model_name='detalleproductosplantillapresupuesto',
            old_name='presupuestoBase',
            new_name='presupuestoPlantilla',
        ),
        migrations.RenameField(
            model_name='detalleserviciosplantillapresupuesto',
            old_name='presupuestoBase',
            new_name='presupuestoPlantilla',
        ),
        migrations.RemoveField(
            model_name='detalleproductosplantillapresupuesto',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='detalleserviciosplantillapresupuesto',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalleproductosplantillapresupuesto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleserviciosplantillapresupuesto',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.servicios'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='detalleproductosplantillapresupuesto',
            table='presupuestos_plantilla_detalle_productos',
        ),
        migrations.AlterModelTable(
            name='detalleserviciosplantillapresupuesto',
            table='presupuestos_plantilla_detalle_servicios',
        ),
        migrations.AlterModelTable(
            name='plantillapresupuestos',
            table='presupuestos_plantilla',
        ),
    ]
