# Generated by Django 3.2.6 on 2021-09-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_auto_20210924_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='estado',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
