# Generated by Django 3.2.6 on 2021-10-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_alter_presupuestos_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillapresupuestos',
            options={'ordering': ['id'], 'verbose_name': 'Plantilla de Presupuesto', 'verbose_name_plural': 'Plantillas de Presupuestos'},
        ),
    ]
