# Generated by Django 3.2.6 on 2021-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='abreviatura',
            field=models.CharField(max_length=20, verbose_name='Abreviatura'),
        ),
    ]
