# Generated by Django 3.2.6 on 2021-09-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_categorias_abreviatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('abreviatura', models.CharField(max_length=20, verbose_name='Abreviatura')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.categorias', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'db_table': 'erp_subcategorias',
                'ordering': ['nombre'],
            },
        ),
    ]
