# Generated by Django 3.2.6 on 2021-12-01 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0001_initial'),
        ('erp', '0002_initial'),
        ('geografico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.categorias', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tiposiva', verbose_name='Tipo de IVA'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='condicionIVA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionesiva', verbose_name='Condición frente al IVA'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='condicionPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Condición de Pago'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='tipoPercepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tipospercepciones', verbose_name='Tipo de Percepción'),
        ),
        migrations.AddField(
            model_name='productos',
            name='iva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tiposiva', verbose_name='Tipo de IVA'),
        ),
        migrations.AddField(
            model_name='productos',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.subcategorias', verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='historicalventas',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.clientes', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalventas',
            name='condicionVenta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.condicionespago', verbose_name='Condición de pago'),
        ),
        migrations.AddField(
            model_name='historicalventas',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalventas',
            name='medioPago',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.mediospago', verbose_name='Medio de pago'),
        ),
        migrations.AddField(
            model_name='historicalventas',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalsubcategorias',
            name='categoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.categorias', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='historicalsubcategorias',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalservicios',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalservicios',
            name='iva',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.tiposiva', verbose_name='Tipo de IVA'),
        ),
        migrations.AddField(
            model_name='historicalproveedores',
            name='condicionIVA',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.condicionesiva', verbose_name='Condición frente al IVA'),
        ),
        migrations.AddField(
            model_name='historicalproveedores',
            name='condicionPago',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.condicionespago', verbose_name='Condición de Pago'),
        ),
        migrations.AddField(
            model_name='historicalproveedores',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproveedores',
            name='localidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geografico.localidades', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='historicalproveedores',
            name='tipoPercepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.tipospercepciones', verbose_name='Tipo de Percepción'),
        ),
        migrations.AddField(
            model_name='historicalproductos',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproductos',
            name='iva',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.tiposiva', verbose_name='Tipo de IVA'),
        ),
        migrations.AddField(
            model_name='historicalproductos',
            name='subcategoria',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.subcategorias', verbose_name='Subcategoría'),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciosventa',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciosventa',
            name='servicio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.servicios'),
        ),
        migrations.AddField(
            model_name='historicaldetalleserviciosventa',
            name='venta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.ventas'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductosventa',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductosventa',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.productos'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductosventa',
            name='venta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.ventas'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductoscompra',
            name='compra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.compras'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductoscompra',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldetalleproductoscompra',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.productos'),
        ),
        migrations.AddField(
            model_name='historicalcompras',
            name='condicionPagoCompra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.condicionespago', verbose_name='Condición de pago'),
        ),
        migrations.AddField(
            model_name='historicalcompras',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompras',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.proveedores', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='historicalcompras',
            name='tipoComprobante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.tiposcomprobantes', verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='historicalcompras',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='condicionIVA',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.condicionesiva', verbose_name='Condición frente al IVA'),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='condicionPago',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.condicionespago', verbose_name='Condición de Pago'),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='localidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geografico.localidades', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='tipoPercepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.tipospercepciones', verbose_name='Tipo de Percepción'),
        ),
        migrations.AddField(
            model_name='historicalcategorias',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleserviciosventa',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.servicios'),
        ),
        migrations.AddField(
            model_name='detalleserviciosventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.ventas'),
        ),
        migrations.AddField(
            model_name='detalleproductosventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos'),
        ),
        migrations.AddField(
            model_name='detalleproductosventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.ventas'),
        ),
        migrations.AddField(
            model_name='detalleproductoscompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.compras'),
        ),
        migrations.AddField(
            model_name='detalleproductoscompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos'),
        ),
        migrations.AddField(
            model_name='compras',
            name='condicionPagoCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Condición de pago'),
        ),
        migrations.AddField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.proveedores', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='compras',
            name='tipoComprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tiposcomprobantes', verbose_name='Tipo de Comprobante'),
        ),
        migrations.AddField(
            model_name='compras',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='condicionIVA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionesiva', verbose_name='Condición frente al IVA'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='condicionPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Condición de Pago'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipoPercepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tipospercepciones', verbose_name='Tipo de Percepción'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategorias',
            unique_together={('categoria', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='productos',
            unique_together={('subcategoria', 'descripcion')},
        ),
        migrations.AlterUniqueTogether(
            name='compras',
            unique_together={('proveedor', 'nroComprobante')},
        ),
    ]
