# Generated by Django 3.2.6 on 2021-09-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_subcategorias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategorias',
            unique_together={('categoria', 'nombre')},
        ),
    ]
