# Generated by Django 3.2.6 on 2021-11-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(null=True, verbose_name='Fecha Límite'),
        ),
        migrations.AlterField(
            model_name='pedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(null=True, verbose_name='Fecha Límite'),
        ),
    ]
