# Generated by Django 3.2.6 on 2021-12-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_alter_prioridades_options'),
        ('erp', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compras',
            unique_together={('proveedor', 'tipoComprobante', 'nroComprobante')},
        ),
    ]
