# Generated by Django 3.2.6 on 2021-09-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_subcategorias_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='abreviatura',
            field=models.CharField(max_length=25, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='abreviatura',
            field=models.CharField(max_length=25, verbose_name='Abreviatura'),
        ),
    ]
