# Generated by Django 3.2.6 on 2021-12-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_compras_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalclientes',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalproveedores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
