# Generated by Django 3.2.6 on 2021-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20211129_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductos',
            name='abreviatura',
            field=models.CharField(default='ABREV', max_length=30, verbose_name='Abreviatura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='abreviatura',
            field=models.CharField(default='ABREV', max_length=30, verbose_name='Abreviatura'),
            preserve_default=False,
        ),
    ]
