# Generated by Django 3.2.6 on 2021-11-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20211113_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosolicitudproveedor',
            name='hash',
            field=models.CharField(max_length=66, null=True, verbose_name='Hash de solicitud'),
        ),
    ]
