# Generated by Django 3.2.6 on 2021-11-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20211130_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedidosolicitud',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='historicaldetallepedidosolicitud',
            name='proveedor',
        ),
    ]
