# Generated by Django 3.2.6 on 2021-11-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_pedidosolicitudproveedor_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosolicitudproveedor',
            name='respuesta',
            field=models.DateTimeField(null=True, verbose_name='Fecha y Hora de respuesta del formulario'),
        ),
        migrations.AlterField(
            model_name='pedidosolicitudproveedor',
            name='visto',
            field=models.DateTimeField(null=True, verbose_name='Fecha y Hora de visto el formulario'),
        ),
    ]
