# Generated by Django 3.2.6 on 2021-09-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210904_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorias',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
