# Generated by Django 3.2.6 on 2021-09-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigoBarras1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo de Barras 1'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigoBarras2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo de Barras 2'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigoProveedor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo de Proveedor'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='reposicion',
            field=models.PositiveIntegerField(default=0, verbose_name='Pedido Reposición'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stockMinimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
    ]
