# Generated by Django 3.2.6 on 2021-09-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20210904_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='esInsumo',
            field=models.BooleanField(default=False, verbose_name='¿Es Insumo?'),
        ),
    ]
