# Generated by Django 3.2.6 on 2021-09-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_productos_esinsumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=9, verbose_name='Margen de Utilidad'),
        ),
    ]
