# Generated by Django 3.2.6 on 2021-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_productos_utilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Abreviatura'),
        ),
    ]
