# Generated by Django 3.2.6 on 2021-09-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_productos_abreviatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['subcategoria', 'descripcion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterUniqueTogether(
            name='productos',
            unique_together={('subcategoria', 'descripcion')},
        ),
        migrations.AlterModelTable(
            name='productos',
            table='erp_productos',
        ),
    ]
