# Generated by Django 3.2.6 on 2021-09-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_alter_tiposiva_options'),
        ('erp', '0012_auto_20210906_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Costo')),
                ('precioVenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/%Y/%m/%d', verbose_name='Imagen')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tiposiva', verbose_name='Tipo de IVA')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'erp_servicios',
                'ordering': ['descripcion'],
            },
        ),
    ]
