# Generated by Django 3.2.6 on 2021-09-07 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografico', '0004_auto_20210904_1549'),
        ('parametros', '0007_alter_condicionesiva_table'),
        ('erp', '0013_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('cuil', models.CharField(max_length=11, verbose_name='Cuil')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Dirección de correo electrónico')),
                ('ctaCte', models.BooleanField(default=False, verbose_name='¿Permitir Cuenta Corriente?')),
                ('limiteCtaCte', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Límite de Cuenta Corriente')),
                ('plazoCtaCte', models.TimeField(blank=True, null=True, verbose_name='Plazo de Vencimiento Cuenta Corriente')),
                ('condicionIVA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionesiva', verbose_name='Condición frente al IVA')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'erp_clientes',
                'ordering': ['razonSocial'],
            },
        ),
    ]
