# Generated by Django 3.2.6 on 2021-09-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='ctaCte',
        ),
    ]
