# Generated by Django 3.2.6 on 2021-09-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_remove_clientes_ctacte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cuil',
            field=models.CharField(max_length=11, unique=True, verbose_name='Cuil'),
        ),
    ]
