# Generated by Django 3.2.6 on 2021-09-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_clientes_cuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cbu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave Bancaria Uniforme (CBU)'),
        ),
    ]
