# Generated by Django 3.2.6 on 2021-09-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_condicionespago'),
        ('erp', '0018_alter_clientes_cbu'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='condicionPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Condición de Pago'),
            preserve_default=False,
        ),
    ]
