# Generated by Django 3.2.6 on 2021-09-09 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografico', '0004_auto_20210904_1549'),
        ('parametros', '0008_condicionespago'),
        ('erp', '0019_clientes_condicionpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('cuit', models.CharField(max_length=11, unique=True, verbose_name='Cuit')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Dirección de correo electrónico')),
                ('cbu', models.CharField(blank=True, max_length=22, null=True, verbose_name='Clave CBU/CVU')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias')),
                ('plazoCtaCte', models.TimeField(blank=True, null=True, verbose_name='Plazo de Vencimiento')),
                ('condicionIVA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionesiva', verbose_name='Condición frente al IVA')),
                ('condicionPago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Condición de Pago')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'erp_proveedores',
                'ordering': ['razonSocial'],
            },
        ),
    ]
