# Generated by Django 3.2.6 on 2021-09-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='plazoCtaCte',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Plazo de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='plazoCtaCte',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Plazo de Vencimiento'),
        ),
    ]
