# Generated by Django 3.2.6 on 2021-09-13 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0013_rename_prioridad_prioridades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0021_auto_20210909_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('percepcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.clientes', verbose_name='Cliente')),
                ('condicionPago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Medio de pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'erp_ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServiciosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.servicios')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta - Productos',
                'verbose_name_plural': 'Detalle de Ventas - Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProductosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta - Productos',
                'verbose_name_plural': 'Detalle de Ventas - Productos',
                'ordering': ['id'],
            },
        ),
    ]
