# Generated by Django 3.2.6 on 2021-09-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0013_rename_prioridad_prioridades'),
        ('erp', '0022_detalleproductosventa_detalleserviciosventa_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='tipoComprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tiposcomprobantes', verbose_name='Tipo de Comprobante'),
        ),
    ]
