# Generated by Django 3.2.6 on 2021-09-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_ventas_tipocomprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='codigo',
            field=models.CharField(max_length=30, unique=True, verbose_name='Codigo'),
        ),
    ]
