# Generated by Django 3.2.6 on 2021-09-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_auto_20210914_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Margen de Utilidad'),
        ),
    ]
