# Generated by Django 3.2.6 on 2021-09-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0015_tipospercepciones'),
        ('erp', '0025_alter_productos_utilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipoPercepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tipospercepciones', verbose_name='Tipo de Percepción'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='tipoPercepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tipospercepciones', verbose_name='Tipo de Percepción'),
        ),
    ]
