# Generated by Django 3.2.6 on 2021-09-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0016_alter_tipospercepciones_percepcion'),
        ('erp', '0026_auto_20210915_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='tipoComprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tiposcomprobantes', verbose_name='Tipo de Comprobante'),
        ),
    ]
