# Generated by Django 3.2.6 on 2021-09-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_alter_ventas_tipocomprobante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='condicionPago',
            new_name='medioPago',
        ),
    ]
