# Generated by Django 3.2.6 on 2021-09-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0017_mediospago'),
        ('erp', '0028_rename_condicionpago_ventas_mediopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='condicionVenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Medio de pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='medioPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.mediospago', verbose_name='Medio de pago'),
        ),
    ]
