# Generated by Django 3.2.6 on 2021-09-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_auto_20210916_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
