# Generated by Django 3.2.6 on 2021-09-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_alter_ventas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductosventa',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detalleproductosventa',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detalleserviciosventa',
            name='precio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detalleserviciosventa',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='iva',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='percepcion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
