# Generated by Django 3.2.6 on 2021-09-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_auto_20210917_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='costo',
            field=models.FloatField(default=0.0, verbose_name='Precio de Costo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVenta',
            field=models.FloatField(default=0.0, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='utilidad',
            field=models.FloatField(default=0.0, verbose_name='Margen de Utilidad'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='costo',
            field=models.FloatField(default=0.0, verbose_name='Precio de Costo'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precioVenta',
            field=models.FloatField(default=0.0, verbose_name='Precio de Venta'),
        ),
    ]
