# Generated by Django 3.2.6 on 2021-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_auto_20210917_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='limiteCtaCte',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Límite de Cuenta Corriente'),
        ),
    ]
