# Generated by Django 3.2.6 on 2021-09-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_alter_clientes_limitectacte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='limiteCtaCte',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Límite de Cuenta Corriente'),
        ),
        migrations.AlterField(
            model_name='detalleproductosventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleproductosventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleserviciosventa',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='detalleserviciosventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='productos',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Costo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Margen de Utilidad'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Costo'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='percepcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
