# Generated by Django 3.2.6 on 2021-09-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_auto_20210917_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estadoVenta',
            field=models.BooleanField(default=True),
        ),
    ]
