# Generated by Django 3.2.6 on 2021-09-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_alter_ventas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['fecha', 'id'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
