# Generated by Django 3.2.6 on 2021-09-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_alter_ventas_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='tipoComprobante',
        ),
    ]
