# Generated by Django 3.2.6 on 2021-09-20 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0022_alter_empresa_cuit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0038_remove_ventas_tipocomprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nroComprobante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Comprobante')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('percepcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estadoCompra', models.BooleanField(default=True)),
                ('medioPago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.mediospago', verbose_name='Medio de pago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.proveedores', verbose_name='Proveedor')),
                ('tipoComprobante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tiposcomprobantes', verbose_name='Tipo de Comprobante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'erp_compras',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProductosCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalle de Compras',
                'ordering': ['id'],
            },
        ),
    ]
