# Generated by Django 3.2.6 on 2021-09-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_compras_detalleproductoscompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleproductoscompra',
            old_name='precio',
            new_name='costo',
        ),
    ]
