# Generated by Django 3.2.6 on 2021-09-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0022_alter_empresa_cuit'),
        ('erp', '0040_rename_precio_detalleproductoscompra_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='medioPago',
        ),
        migrations.AddField(
            model_name='compras',
            name='condicionPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Condición de pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipoPercepcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tipospercepciones', verbose_name='Tipo de Percepción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='condicionVenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.condicionespago', verbose_name='Condición de pago'),
        ),
    ]
