# Generated by Django 3.2.6 on 2021-09-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0041_auto_20210921_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compras',
            old_name='condicionPago',
            new_name='condicionPagoCompra',
        ),
    ]
