# Generated by Django 3.2.6 on 2021-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0042_rename_condicionpago_compras_condicionpagocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de correo electrónico'),
        ),
    ]
