# Generated by Django 3.2.6 on 2021-09-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_alter_clientes_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleserviciosventa',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta - Servicios', 'verbose_name_plural': 'Detalle de Ventas - Servicios'},
        ),
    ]
