# Generated by Django 3.2.6 on 2021-10-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_alter_detalleserviciosventa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='chatIdCliente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
