# Generated by Django 3.2.6 on 2021-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_auto_20211004_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='codigoBarras2',
        ),
        migrations.AlterField(
            model_name='compras',
            name='nroComprobante',
            field=models.CharField(default=1, max_length=100, verbose_name='Número de Comprobante'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='compras',
            unique_together={('proveedor', 'nroComprobante')},
        ),
    ]
