# Generated by Django 3.2.6 on 2021-10-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0034_auto_20211002_1514'),
        ('erp', '0046_auto_20211006_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='tipoPercepcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='parametros.tipospercepciones', verbose_name='Tipo de Percepción'),
            preserve_default=False,
        ),
    ]
