# Generated by Django 3.2.6 on 2021-10-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_alter_proveedores_tipopercepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Solicitud de Pedido',
                'verbose_name_plural': 'Solicitudes de Pedidos',
                'db_table': 'erp_pedidos_solicitud',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.pedidossolicitud')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Pedido',
                'verbose_name_plural': 'Detalle de Solicitudes de Pedidos',
                'ordering': ['id'],
            },
        ),
    ]
