# Generated by Django 3.2.6 on 2021-10-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_clientes_chatidcliente'),
        ('erp', '0047_alter_proveedores_tipopercepcion'),
    ]

    operations = [
    ]
