# Generated by Django 3.2.6 on 2021-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_detallepedidosolicitud_pedidossolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidossolicitud',
            name='estado',
            field=models.BooleanField(blank=True, default='', null=True),
        ),
    ]
