# Generated by Django 3.2.6 on 2021-10-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0049_alter_pedidossolicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedidosolicitud',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp.proveedores', verbose_name='Proveedor'),
        ),
    ]
