# Generated by Django 3.2.6 on 2021-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_alter_detallepedidosolicitud_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='trabajo',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='ID Trabajo Asociado'),
        ),
    ]
