# Generated by Django 3.2.6 on 2021-10-26 23:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0051_ventas_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 23, 16, 17, 925165, tzinfo=utc), verbose_name='Fecha Límite'),
        ),
    ]
