# Generated by Django 3.2.6 on 2021-10-27 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0053_alter_pedidossolicitud_fechalimite'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='esfuerzo',
            field=models.PositiveIntegerField(default=50, verbose_name='Esfuerzo'),
        ),
        migrations.AlterField(
            model_name='pedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 11, 37, 24, 320568, tzinfo=utc), verbose_name='Fecha Límite'),
        ),
    ]
