# Generated by Django 3.2.6 on 2021-10-27 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_auto_20211027_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descuentaStock',
            field=models.BooleanField(default=True, verbose_name='¿Descuenta?'),
        ),
        migrations.AlterField(
            model_name='pedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 15, 9, 23, 682836, tzinfo=utc), verbose_name='Fecha Límite'),
        ),
    ]
