# Generated by Django 3.2.6 on 2021-10-27 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0056_auto_20211027_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 15, 9, 53, 774734, tzinfo=utc), verbose_name='Fecha Límite'),
        ),
    ]
