# Generated by Django 3.2.6 on 2021-10-27 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0057_alter_pedidossolicitud_fechalimite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 15, 10, 55, 970916, tzinfo=utc), verbose_name='Fecha Límite'),
        ),
    ]
