# Generated by Django 3.2.6 on 2021-10-27 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0060_alter_pedidossolicitud_fechalimite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 12, 12, 52, 334970), verbose_name='Fecha Límite'),
        ),
    ]
