# Generated by Django 3.2.6 on 2021-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0061_alter_pedidossolicitud_fechalimite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidossolicitud',
            name='fechaLimite',
            field=models.DateTimeField(verbose_name='Fecha Límite'),
        ),
    ]
