# Generated by Django 3.2.6 on 2021-10-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0062_alter_pedidossolicitud_fechalimite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='esfuerzo',
            field=models.PositiveIntegerField(default=20, verbose_name='Esfuerzo'),
        ),
    ]
