# Generated by Django 3.2.6 on 2021-10-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_merge_20211009_1441'),
        ('erp', '0063_alter_servicios_esfuerzo'),
    ]

    operations = [
    ]
