# Generated by Django 3.2.6 on 2021-10-30 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0036_alter_estadoparametros_estadoplanificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0063_alter_servicios_esfuerzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('abreviatura', models.CharField(blank=True, max_length=30, null=True, verbose_name='Abreviatura')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Codigo')),
                ('codigoProveedor', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Codigo de Proveedor')),
                ('codigoBarras1', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Codigo de Barras 1')),
                ('stockReal', models.IntegerField(default=0, verbose_name='Stock Real')),
                ('stockMinimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('reposicion', models.PositiveIntegerField(default=0, verbose_name='Pedido Reposición')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Costo')),
                ('utilidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Margen de Utilidad')),
                ('precioVenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de Venta')),
                ('imagen', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion Física')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('esInsumo', models.BooleanField(default=False, verbose_name='¿Es Insumo?')),
                ('descuentaStock', models.BooleanField(default=True, verbose_name='¿Descuenta Stock?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('iva', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='parametros.tiposiva', verbose_name='Tipo de IVA')),
                ('subcategoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='erp.subcategorias', verbose_name='Subcategoría')),
            ],
            options={
                'verbose_name': 'historical Producto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
