# Generated by Django 3.2.6 on 2021-11-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0045_clientes_chatidcliente'),
        ('erp', '0065_historicalservicios'),
    ]

    operations = [
    ]
