# Generated by Django 3.2.6 on 2021-11-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0066_merge_20211101_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='chatIdCliente',
        ),
    ]
