# Generated by Django 3.2.6 on 2021-11-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0068_historicaldetalleproductosventa_historicaldetalleserviciosventa_historicalventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldetalleproductosventa',
            name='venta_history_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
