# Generated by Django 3.2.6 on 2021-11-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0069_historicaldetalleproductosventa_venta_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldetalleproductosventa',
            name='venta_history_id',
            field=models.PositiveIntegerField(default=17),
        ),
    ]
