# Generated by Django 3.2.6 on 2021-11-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0072_auto_20211103_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldetalleproductosventa',
            name='venta_history_id',
        ),
        migrations.RemoveField(
            model_name='historicaldetalleserviciosventa',
            name='venta_history_id',
        ),
    ]
