# Generated by Django 3.2.6 on 2021-11-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0064_merge_20211028_0708'),
        ('erp', '0073_auto_20211104_1308'),
    ]

    operations = [
    ]
