# Generated by Django 3.2.6 on 2021-11-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0075_historicalcategorias_historicalclientes_historicalcompras_historicaldetallepedidosolicitud_historica'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallepedidosolicitud',
            table='erp_pedidos_solicitud_detalle',
        ),
        migrations.AlterModelTable(
            name='detalleproductoscompra',
            table='erp_compras_detalle',
        ),
        migrations.AlterModelTable(
            name='detalleproductosventa',
            table='erp_ventas_detalle_productos',
        ),
        migrations.AlterModelTable(
            name='detalleserviciosventa',
            table='erp_ventas_detalle_servicios',
        ),
        migrations.CreateModel(
            name='PedidoSolicitudProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado', models.DateTimeField(verbose_name='Fecha y Hora de envío correo electrónico')),
                ('visto', models.DateTimeField(verbose_name='Fecha y Hora de visto el formulario')),
                ('respuesta', models.DateTimeField(verbose_name='Fecha y Hora de respuesta del formulario')),
                ('pedidoSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.pedidossolicitud', verbose_name='Pedido de Solicitud')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Solicitud de Pedido Proveedor',
                'verbose_name_plural': 'Solicitudes de Pedidos Proveedor',
                'db_table': 'erp_pedidos_solicitud_proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('estado', models.BooleanField(blank=True, default='', null=True)),
                ('pedidoSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.pedidossolicitud', verbose_name='Pedido de Solicitud')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'erp_pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoSolicitudProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('pedidoSolicitudProveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.pedidosolicitudproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud de Pedido',
                'verbose_name_plural': 'Detalle de Solicitudes de Pedidos',
                'db_table': 'erp_pedidos_solicitud_proveedor_detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.productos', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalle de Pedidos',
                'db_table': 'erp_pedidos_detalle',
                'ordering': ['id'],
            },
        ),
    ]
