# Generated by Django 3.2.6 on 2021-11-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0076_auto_20211110_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosolicitudproveedor',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='pedidosolicitudproveedor',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='pedidosolicitudproveedor',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
