# Generated by Django 3.2.6 on 2021-10-19 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notificacionesGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNotificacion', models.DateTimeField()),
                ('estado', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('resuelta', 'Semanalmente'), ('vista', 'Mensualmente'), ('urgente', 'Urgente')], max_length=9)),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=254)),
                ('fechaRevisionUser', models.DateTimeField(blank=True, null=True)),
                ('enviadoAUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario al que se le envió la notif')),
            ],
            options={
                'verbose_name': 'Notificación genérica',
                'verbose_name_plural': 'Notificaciones Genéricas',
                'db_table': 'notif_notif_generica',
                'ordering': ['fechaNotificacion'],
            },
        ),
    ]
