# Generated by Django 3.2.6 on 2021-11-11 15:19

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalnotificacionesGenerales',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fechaNotificacion', models.DateTimeField()),
                ('estado', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('vista', 'Vista'), ('urgente', 'Urgente')], max_length=9)),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=254)),
                ('fechaRevisionUser', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Notificación genérica',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='notificacionesGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNotificacion', models.DateTimeField()),
                ('estado', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('vista', 'Vista'), ('urgente', 'Urgente')], max_length=9)),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=254)),
                ('fechaRevisionUser', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificación genérica',
                'verbose_name_plural': 'Notificaciones Genéricas',
                'db_table': 'notif_notif_generica',
                'ordering': ['fechaNotificacion'],
            },
        ),
    ]
