# Generated by Django 3.2.6 on 2021-10-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif_channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionesgenerales',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('vista', 'Vista'), ('urgente', 'Urgente')], max_length=9),
        ),
    ]
