# Generated by Django 3.2.6 on 2021-11-10 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notif_channel', '0002_alter_notificacionesgenerales_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalnotificacionesGenerales',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fechaNotificacion', models.DateTimeField()),
                ('estado', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('vista', 'Vista'), ('urgente', 'Urgente')], max_length=9)),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=254)),
                ('fechaRevisionUser', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('enviadoAUser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario al que se le envió la notif')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Notificación genérica',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
