# Generated by Django 3.2.6 on 2021-11-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuarios',
            name='realizaTrabajos',
            field=models.BooleanField(default=False, verbose_name='¿Realiza Trabajos?'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='realizaTrabajos',
            field=models.BooleanField(default=False, verbose_name='¿Realiza Trabajos?'),
        ),
    ]
