# Generated by Django 3.2.6 on 2021-08-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geografico', '0003_auto_20210823_1719'),
        ('usuarios', '0002_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geografico.localidades', verbose_name='Localidad'),
        ),
    ]
