# Generated by Django 3.2.6 on 2021-08-24 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210824_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fechaIngreso',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
