# Generated by Django 3.2.6 on 2021-08-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuarios_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cuil',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Cuil'),
        ),
    ]
