# Generated by Django 3.2.6 on 2021-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuarios_cuil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fechaIngreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
