# Generated by Django 3.2.6 on 2021-09-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuarios_fechaingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, default='empty.png', null=True, upload_to='usuarios/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
