# Generated by Django 3.2.6 on 2021-09-09 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuarios_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='tipoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tiposusuarios', verbose_name='Tipo de Usuario'),
        ),
    ]
