# Generated by Django 3.2.6 on 2021-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuarios_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
