# Generated by Django 3.2.6 on 2021-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_usuarios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='legajo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Legajo'),
        ),
    ]
