# Generated by Django 3.2.6 on 2021-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuarios_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='chatIdUsuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
