# Generated by Django 3.2.6 on 2021-10-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuarios_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposusuarios',
            name='realizaTrabajos',
            field=models.BooleanField(default=False, verbose_name='¿Realiza trabajos?'),
        ),
    ]
