# Generated by Django 3.2.6 on 2021-10-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_tiposusuarios_realizatrabajos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cuil',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Cuil'),
        ),
    ]
