# Generated by Django 3.2.6 on 2021-10-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuarios_chatidusuario'),
        ('usuarios', '0014_alter_usuarios_cuil'),
    ]

    operations = [
    ]
