# Generated by Django 3.2.6 on 2021-11-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_usuarios_chatidusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='tipoUsuario',
        ),
        migrations.DeleteModel(
            name='TiposUsuarios',
        ),
    ]
