# Generated by Django 3.2.6 on 2021-11-29 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diasAvisoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasAntelacion', models.PositiveIntegerField(default=0)),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dias a recordar',
                'verbose_name_plural': 'Dias a recordar',
                'db_table': 'agenda_diasAvisoEvento',
                'ordering': ['diasAntelacion'],
            },
        ),
        migrations.CreateModel(
            name='eventosAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(default=django.utils.timezone.now)),
                ('fechaNotificacion', models.DateField()),
                ('fechaFinalizacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('vencido', models.BooleanField(default=False)),
                ('resuelto', models.BooleanField(default=False)),
                ('repeticion', models.CharField(blank=True, choices=[('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensualmente')], max_length=7)),
                ('estado', models.BooleanField(default=True)),
                ('horaResolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento Agenda',
                'verbose_name_plural': 'Eventos Agenda',
                'db_table': 'agenda_eventosAgenda',
                'ordering': ['fechaCreacion'],
            },
        ),
        migrations.CreateModel(
            name='HistoricaldiasAvisoEvento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('diasAntelacion', models.PositiveIntegerField(default=0)),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Dias a recordar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricaleventosAgenda',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fechaCreacion', models.DateField(default=django.utils.timezone.now)),
                ('fechaNotificacion', models.DateField()),
                ('fechaFinalizacion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('vencido', models.BooleanField(default=False)),
                ('resuelto', models.BooleanField(default=False)),
                ('repeticion', models.CharField(blank=True, choices=[('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensualmente')], max_length=7)),
                ('estado', models.BooleanField(default=True)),
                ('horaResolucion', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Evento Agenda',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalnotificacionUsuarios',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Notificacion Usuarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricaltiposEvento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='Nombre')),
                ('horarioRecordatorio', models.TimeField()),
                ('recordarSistema', models.BooleanField(default=True)),
                ('recordarTelegram', models.BooleanField()),
                ('estado', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Tipo de Evento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='tiposEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('horarioRecordatorio', models.TimeField()),
                ('recordarSistema', models.BooleanField(default=True)),
                ('recordarTelegram', models.BooleanField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Eventos',
                'db_table': 'agenda_tiposEventos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='notificacionUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('tipoEvento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.tiposevento', verbose_name='tipoEvento')),
            ],
            options={
                'verbose_name': 'Notificacion Usuarios',
                'verbose_name_plural': 'Notificacion Usuarios',
                'db_table': 'agenda_notificacionUsuarios',
                'ordering': ['tipoEvento'],
            },
        ),
    ]
