# Generated by Django 3.2.6 on 2021-12-01 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionusuarios',
            name='usuarioNotif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioAsoc'),
        ),
        migrations.AddField(
            model_name='historicaltiposevento',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnotificacionusuarios',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnotificacionusuarios',
            name='tipoEvento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agenda.tiposevento', verbose_name='tipoEvento'),
        ),
        migrations.AddField(
            model_name='historicalnotificacionusuarios',
            name='usuarioNotif',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='UsuarioAsoc'),
        ),
        migrations.AddField(
            model_name='historicaleventosagenda',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleventosagenda',
            name='resueltoPor_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que resolvió el evento'),
        ),
        migrations.AddField(
            model_name='historicaleventosagenda',
            name='tipoEvento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agenda.tiposevento', verbose_name='tipoEvento'),
        ),
        migrations.AddField(
            model_name='historicaldiasavisoevento',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventosagenda',
            name='resueltoPor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que resolvió el evento'),
        ),
        migrations.AddField(
            model_name='eventosagenda',
            name='tipoEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.tiposevento', verbose_name='tipoEvento'),
        ),
    ]
