# Generated by Django 3.2.6 on 2021-09-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_tiposevento_usuarionotif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosagenda',
            name='fechaNotificacion',
            field=models.DateField(),
        ),
    ]
