# Generated by Django 3.2.6 on 2021-12-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltiposevento',
            name='deSistema',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tiposevento',
            name='deSistema',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
    ]
