# Generated by Django 3.2.6 on 2021-09-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_eventosagenda_repeticion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosagenda',
            name='repeticion',
            field=models.CharField(blank=True, choices=[('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensualmente')], default='none', max_length=7),
        ),
    ]
