# Generated by Django 3.2.6 on 2021-09-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20210902_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposevento',
            old_name='recordarWpp',
            new_name='recordarTelegram',
        ),
    ]
