# Generated by Django 3.2.6 on 2021-09-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_eventosagenda_repeticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='cantNotifSistema',
            field=models.IntegerField(default=0, verbose_name='cantidad de veces notificadas'),
        ),
        migrations.AddField(
            model_name='eventosagenda',
            name='cantNotifTelegram',
            field=models.IntegerField(default=0, verbose_name='cantidad de veces notificadas'),
        ),
    ]
