# Generated by Django 3.2.6 on 2021-09-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_rename_recordarwpp_tiposevento_recordartelegram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposevento',
            old_name='tiempoRecordatorio',
            new_name='horarioRecordatorio',
        ),
    ]
