# Generated by Django 3.2.6 on 2021-09-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_eventosagenda_cantnotiftelegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='ultimaNotificacionSist',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventosagenda',
            name='ultimaNotificacionTel',
            field=models.DateField(blank=True, null=True),
        ),
    ]
