# Generated by Django 3.2.6 on 2021-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_auto_20210918_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='ultimaVistaNotifiSist',
            field=models.DateField(blank=True, null=True),
        ),
    ]
