# Generated by Django 3.2.6 on 2021-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_eventosagenda_ultimavistanotifisist'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='ultimaVistaNotifiTel',
            field=models.DateField(blank=True, null=True),
        ),
    ]
