# Generated by Django 3.2.6 on 2021-09-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_auto_20210921_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasavisoevento',
            options={'ordering': ['tipoEvento'], 'verbose_name': 'Diaa a recordar', 'verbose_name_plural': 'Dias a recordar'},
        ),
        migrations.AlterModelTable(
            name='diasavisoevento',
            table='agenda_diasAvisoEvento',
        ),
    ]
