# Generated by Django 3.2.6 on 2021-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20210921_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasavisoevento',
            name='diasAntelacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
