# Generated by Django 3.2.6 on 2021-09-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_diasavisoevento_diasantelacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasavisoevento',
            options={'ordering': ['diasAntelacion'], 'verbose_name': 'Diaa a recordar', 'verbose_name_plural': 'Dias a recordar'},
        ),
        migrations.RemoveField(
            model_name='diasavisoevento',
            name='tipoEvento',
        ),
    ]
