# Generated by Django 3.2.6 on 2021-09-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_auto_20210921_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasavisoevento',
            options={'ordering': ['diasAntelacion'], 'verbose_name': 'Dias a recordar', 'verbose_name_plural': 'Dias a recordar'},
        ),
    ]
