# Generated by Django 3.2.6 on 2021-09-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_alter_diasavisoevento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diasavisoevento',
            name='domingo',
        ),
    ]
