# Generated by Django 3.2.6 on 2021-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_remove_diasavisoevento_domingo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasavisoevento',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diasavisoevento',
            name='jueves',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diasavisoevento',
            name='lunes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diasavisoevento',
            name='martes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diasavisoevento',
            name='miercoles',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diasavisoevento',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diasavisoevento',
            name='viernes',
            field=models.BooleanField(default=True),
        ),
    ]
