# Generated by Django 3.2.6 on 2021-09-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_auto_20210921_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='fechaFinalizacion',
            field=models.DateField(null=True),
        ),
    ]
