# Generated by Django 3.2.6 on 2021-09-21 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_eventosagenda_fechafinalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosagenda',
            name='fechaFinalizacion',
            field=models.DateField(default=datetime.datetime(2021, 9, 21, 15, 43, 54, 449277)),
            preserve_default=False,
        ),
    ]
