# Generated by Django 3.2.6 on 2021-09-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_alter_eventosagenda_fechafinalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosagenda',
            name='fechaFinalizacion',
            field=models.DateField(blank=True),
        ),
    ]
