# Generated by Django 3.2.6 on 2021-09-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_alter_eventosagenda_fechafinalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='vencido',
            field=models.BooleanField(default=False),
        ),
    ]
