# Generated by Django 3.2.6 on 2021-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_eventosagenda_vencido'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
