# Generated by Django 3.2.6 on 2021-09-30 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0023_eventosagenda_resuelto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposevento',
            name='usuarioNotif',
        ),
        migrations.CreateModel(
            name='notificacionUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.tiposevento', verbose_name='tipoEvento')),
                ('usuarioNotif', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioAsoc')),
            ],
        ),
    ]
