# Generated by Django 3.2.6 on 2021-09-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0024_auto_20210930_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacionusuarios',
            options={'ordering': ['tipoEvento'], 'verbose_name': 'Notificacion Usuarios', 'verbose_name_plural': 'Notificacion Usuarios'},
        ),
        migrations.AlterModelTable(
            name='notificacionusuarios',
            table='agenda_notificacionUsuarios',
        ),
    ]
