# Generated by Django 3.2.6 on 2021-10-02 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0025_auto_20210930_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosagenda',
            name='cantNotifSistema',
        ),
        migrations.RemoveField(
            model_name='eventosagenda',
            name='cantNotifTelegram',
        ),
        migrations.RemoveField(
            model_name='eventosagenda',
            name='ultimaNotificacionSist',
        ),
        migrations.RemoveField(
            model_name='eventosagenda',
            name='ultimaNotificacionTel',
        ),
        migrations.RemoveField(
            model_name='eventosagenda',
            name='ultimaVistaNotifiSist',
        ),
        migrations.RemoveField(
            model_name='eventosagenda',
            name='ultimaVistaNotifiTel',
        ),
        migrations.CreateModel(
            name='notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificarSist', models.BooleanField(default=True)),
                ('notificarTel', models.BooleanField(default=True)),
                ('notificacion', models.CharField(blank=True, choices=[('yes', 'Si'), ('no', 'No'), ('passive', 'add pero no notif'), ('pending', 'Pendiente'), ('urgent', 'Urgente')], max_length=7)),
                ('eventoAsoc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.eventosagenda', verbose_name='Evento Asociado')),
                ('usuarioNotif', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario a Notificar')),
            ],
        ),
        migrations.CreateModel(
            name='detalleNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultNotifSist', models.DateField(blank=True, null=True)),
                ('ultNotifTel', models.DateField(blank=True, null=True)),
                ('cantNotifTel', models.IntegerField(blank=True, default=0, verbose_name='cantidad de veces notificadas')),
                ('cantNotifSist', models.IntegerField(blank=True, default=0, verbose_name='cantidad de veces notificadas')),
                ('resolDateTel', models.DateField(blank=True, null=True)),
                ('resolDateSist', models.DateField(blank=True, null=True)),
                ('ultVistaUserSist', models.DateField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agenda.notificaciones', verbose_name='Notificacion Asociada')),
                ('resueltaPorUserSist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resUserSist', to=settings.AUTH_USER_MODEL, verbose_name='Usuario resolucion Sist')),
                ('resueltaPorUserTel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resUserTel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario resolucion Tel')),
                ('vistaPorUserSist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario vista Sist')),
            ],
        ),
    ]
