# Generated by Django 3.2.6 on 2021-10-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0026_auto_20211002_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallenotificacion',
            options={'ordering': ['notificacion'], 'verbose_name': 'detalle notificacion', 'verbose_name_plural': 'detalles notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='notificaciones',
            options={'ordering': ['eventoAsoc'], 'verbose_name': 'Notificacion fuente', 'verbose_name_plural': 'Notificaciones fuente'},
        ),
        migrations.AlterModelTable(
            name='detallenotificacion',
            table='agenda_detalleNotificacion',
        ),
        migrations.AlterModelTable(
            name='notificaciones',
            table='agenda_notificaciones',
        ),
    ]
