# Generated by Django 3.2.6 on 2021-10-02 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0029_auto_20211002_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenotificacion',
            name='resueltaPorUserTel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resUserTel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario resolucion Tel'),
        ),
        migrations.AlterField(
            model_name='detallenotificacion',
            name='vistaPorUserSist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario vista Sist'),
        ),
    ]
