# Generated by Django 3.2.6 on 2021-10-02 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0030_auto_20211002_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='cantNotifSist',
            field=models.IntegerField(blank=True, default=0, verbose_name='cantidad de veces notificadas'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='cantNotifTel',
            field=models.IntegerField(blank=True, default=0, verbose_name='cantidad de veces notificadas'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='resolDateSist',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='resolDateTel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='resueltaPorUserSist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resUserSist', to=settings.AUTH_USER_MODEL, verbose_name='Usuario resolucion Sist'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='resueltaPorUserTel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resUserTel', to=settings.AUTH_USER_MODEL, verbose_name='Usuario resolucion Tel'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='ultNotifSist',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='ultNotifTel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='ultVistaUserSist',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='vistaPorUserSist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vistaUserSist', to=settings.AUTH_USER_MODEL, verbose_name='Usuario vista Sist'),
        ),
        migrations.DeleteModel(
            name='detalleNotificacion',
        ),
    ]
