# Generated by Django 3.2.6 on 2021-10-02 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0031_auto_20211002_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='resueltaPorUserSist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resUserSist', to=settings.AUTH_USER_MODEL, verbose_name='Usuario resolucion Sist'),
        ),
    ]
