# Generated by Django 3.2.6 on 2021-10-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0032_alter_notificaciones_resueltaporusersist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='resolDateSist',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='resolDateTel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='ultNotifSist',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='ultNotifTel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='ultVistaUserSist',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
