# Generated by Django 3.2.6 on 2021-10-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0033_auto_20211003_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='resolDateSist',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='resolDateTel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='ultNotifSist',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='ultNotifTel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='ultVistaUserSist',
            field=models.DateField(blank=True, null=True),
        ),
    ]
