# Generated by Django 3.2.6 on 2021-10-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0034_auto_20211003_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
