# Generated by Django 3.2.6 on 2021-10-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0035_eventosagenda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposevento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
