# Generated by Django 3.2.6 on 2021-10-22 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0036_tiposevento_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notificaciones',
        ),
    ]
