# Generated by Django 3.2.6 on 2021-10-22 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0037_delete_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='resueltoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuario que resolvió el evento'),
        ),
        migrations.AlterField(
            model_name='eventosagenda',
            name='resuelto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
