# Generated by Django 3.2.6 on 2021-10-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0038_auto_20211022_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosagenda',
            name='resueltoPor',
        ),
        migrations.AlterField(
            model_name='eventosagenda',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
