# Generated by Django 3.2.6 on 2021-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0039_auto_20211022_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionusuarios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
