# Generated by Django 3.2.6 on 2021-10-29 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0040_notificacionusuarios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosagenda',
            name='horaResolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventosagenda',
            name='resueltoPor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que resolvió el evento'),
        ),
    ]
